# Generated by Django 5.2.6 on 2025-11-03 12:59

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('intercorrencia_uuid', models.UUIDField(db_index=True, help_text='UUID da intercorrência no micro serviço de intercorrências', verbose_name='UUID da Intercorrência')),
                ('perfil', models.CharField(choices=[('diretor', 'Diretor'), ('dre', 'DRE'), ('gipe', 'GIPE')], help_text='Perfil do usuário que anexou o arquivo', max_length=20, verbose_name='Perfil que anexou')),
                ('categoria', models.CharField(choices=[('boletim_ocorrencia', 'Boletim de ocorrência'), ('registro_ocorrencia_interno', 'Registro de ocorrência interno'), ('protocolo_conselho_tutelar', 'Protocolo do Conselho Tutelar'), ('instrucao_normativa_20_2020', 'Instrução normativa 20/2020'), ('relatorio_naapa', 'Relatório do NAAPA'), ('relatorio_cefai', 'Relatório do CEFAI'), ('relatorio_sts', 'Relatório do STS'), ('relatorio_cpca', 'Relatório do CPCA'), ('oficio_gcm', 'Ofício Guarda Civil Metropolitana (GCM)'), ('boletim_ocorrencia', 'Boletim de ocorrência'), ('registro_intercorrencia', 'Registro de intercorrência'), ('protocolo_conselho_tutelar', 'Protocolo Conselho Tutelar'), ('instrucao_normativa_20_2020', 'Instrução Normativa 20/2020'), ('relatorio_naapa', 'Relatório do NAAPA'), ('relatorio_supervisao_escolar', 'Relatório da Supervisão Escolar'), ('relatorio_cefai', 'Relatório do CEFAI'), ('relatorio_sts', 'Relatório do STS'), ('relatorio_cpca', 'Relatório do CPCA'), ('oficio_gcm', 'Ofício Guarda Civil Metropolitana (GCM)')], help_text='Categoria/tipo do documento anexado', max_length=50, verbose_name='Categoria do anexo')),
                ('arquivo', models.FileField(upload_to='anexos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'mp4', 'pdf', 'xlsx', 'docx', 'txt'])], verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome original do arquivo')),
                ('tamanho_bytes', models.BigIntegerField(help_text='Tamanho do arquivo em bytes', verbose_name='Tamanho do arquivo (bytes)')),
                ('tipo_mime', models.CharField(help_text='Tipo MIME do arquivo', max_length=100, verbose_name='Tipo MIME')),
                ('usuario_username', models.CharField(help_text='Username do usuário que anexou o arquivo', max_length=150, verbose_name='Username do usuário')),
                ('usuario_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome do usuário')),
                ('ativo', models.BooleanField(default=True, help_text="Se False, o arquivo foi 'excluído' logicamente", verbose_name='Ativo')),
                ('excluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('excluido_por', models.CharField(blank=True, max_length=150, verbose_name='Excluído por')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ('-criado_em',),
                'indexes': [models.Index(fields=['intercorrencia_uuid', 'perfil'], name='anexos_anex_interco_0a76ac_idx'), models.Index(fields=['intercorrencia_uuid', 'ativo'], name='anexos_anex_interco_cb8ccd_idx'), models.Index(fields=['usuario_username'], name='anexos_anex_usuario_9ac7ff_idx'), models.Index(fields=['categoria'], name='anexos_anex_categor_6b02ee_idx')],
            },
        ),
    ]
