# Generated by Django 5.2.6 on 2025-11-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='perfil',
            field=models.CharField(choices=[('diretor', 'Diretor'), ('assistente', 'Assistente'), ('dre', 'DRE'), ('gipe', 'GIPE')], help_text='Perfil do usuário que anexou o arquivo', max_length=20, verbose_name='Perfil que anexou'),
        ),
    ]
