# Generated by Django 5.2.6 on 2026-03-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexos', '0002_alter_anexo_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='categoria',
            field=models.CharField(choices=[('boletim_ocorrencia', 'Boletim de ocorrência'), ('protocolo_boletim_ocorrencia', 'Protocolo do boletim de ocorrência'), ('registro_ocorrencia_interno', 'Registro de ocorrência interno'), ('imagens', 'Imagens'), ('relatorio_naapa', 'Relatório do NAAPA'), ('relatorio_cefai', 'Relatório do CEFAI'), ('relatorio_sts', 'Relatório do STS'), ('relatorio_cpca', 'Relatório do CPCA'), ('oficio_gcm', 'Ofício Guarda Civil Metropolitana (GCM)'), ('boletim_ocorrencia', 'Boletim de ocorrência'), ('registro_intercorrencia', 'Registro de intercorrência'), ('protocolo_conselho_tutelar', 'Protocolo Conselho Tutelar'), ('instrucao_normativa_20_2020', 'Instrução Normativa 20/2020'), ('relatorio_naapa', 'Relatório do NAAPA'), ('relatorio_supervisao_escolar', 'Relatório da Supervisão Escolar'), ('relatorio_cefai', 'Relatório do CEFAI'), ('relatorio_sts', 'Relatório do STS'), ('relatorio_cpca', 'Relatório do CPCA'), ('oficio_gcm', 'Ofício Guarda Civil Metropolitana (GCM)')], help_text='Categoria/tipo do documento anexado', max_length=50, verbose_name='Categoria do anexo'),
        ),
    ]
