# Generated by Django 5.2.6 on 2026-03-25 17:19

from django.db import migrations, models
 
BOLETIM_OCORRENCIA_LABEL = 'Boletim de ocorrência (B.O)'


class Migration(migrations.Migration):

    dependencies = [
        ('anexos', '0003_alter_anexo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='categoria',
            field=models.CharField(choices=[('boletim_ocorrencia', BOLETIM_OCORRENCIA_LABEL), ('protocolo_boletim_ocorrencia', 'Protocolo do boletim de ocorrência'), ('registro_ocorrencia_interno', 'Registro de ocorrência interno'), ('imagens', 'Imagens'), ('boletim_ocorrencia', BOLETIM_OCORRENCIA_LABEL), ('oficio', 'Ofício'), ('boletim_ocorrencia', BOLETIM_OCORRENCIA_LABEL), ('oficio', 'Ofício')], help_text='Categoria/tipo do documento anexado', max_length=50, verbose_name='Categoria do anexo'),
        ),
    ]
