# Generated by Django 5.2.6 on 2026-04-16 16:02

from django.db import migrations, models

BOLETIM_OCORRENCIA_LABEL = 'Boletim de ocorrência (B.O)'


class Migration(migrations.Migration):

    dependencies = [
        ('anexos', '0004_alter_anexo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='categoria',
            field=models.CharField(choices=[('boletim_ocorrencia', BOLETIM_OCORRENCIA_LABEL), ('protocolo_boletim_ocorrencia', 'Protocolo do boletim de ocorrência'), ('registro_ocorrencia_interno', 'Registro de ocorrência interno'), ('imagens', 'Imagens'), ('boletim_ocorrencia', BOLETIM_OCORRENCIA_LABEL), ('oficio', 'Ofício'), ('outro_documento', 'Outro documento'), ('boletim_ocorrencia', BOLETIM_OCORRENCIA_LABEL), ('oficio', 'Ofício'), ('outro_documento', 'Outro documento')], help_text='Categoria/tipo do documento anexado', max_length=50, verbose_name='Categoria do anexo'),
        ),
    ]
